language:
   - cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_script:
    - wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl && chmod a+x checkpatch.pl
    - wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/spelling.txt
    - echo "invalid.struct.name" >const_structs.checkpatch
    - find . -name "*.c" -o -name "*.cpp" -o -name "*.h" | xargs -I {} checkpatch.pl --ignore NEW_TYPEDEFS,CAMELCASE,LEADING_SPACE,CODE_INDENT,CONST_STRUCT --terse --no-tree --strict --file $c

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make -j3
    - ctest
